/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AddNew` | `/AddNew`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/doctor`; params?: Router.UnknownInputParams; } | { pathname: `/feats/MedicalReport`; params?: Router.UnknownInputParams; } | { pathname: `/feats/ResultModal`; params?: Router.UnknownInputParams; } | { pathname: `/feats/dhancha`; params?: Router.UnknownInputParams; } | { pathname: `/feats/dvit`; params?: Router.UnknownInputParams; } | { pathname: `/feats/jagrook`; params?: Router.UnknownInputParams; } | { pathname: `/feats/medi-sight`; params?: Router.UnknownInputParams; } | { pathname: `/hospital/data_up`; params?: Router.UnknownInputParams; } | { pathname: `/hospital`; params?: Router.UnknownInputParams; } | { pathname: `/hospital/profile`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/login/signin`; params?: Router.UnknownInputParams; } | { pathname: `/login/signup`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AddNew` | `/AddNew`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `/doctor`; params?: Router.UnknownOutputParams; } | { pathname: `/feats/MedicalReport`; params?: Router.UnknownOutputParams; } | { pathname: `/feats/ResultModal`; params?: Router.UnknownOutputParams; } | { pathname: `/feats/dhancha`; params?: Router.UnknownOutputParams; } | { pathname: `/feats/dvit`; params?: Router.UnknownOutputParams; } | { pathname: `/feats/jagrook`; params?: Router.UnknownOutputParams; } | { pathname: `/feats/medi-sight`; params?: Router.UnknownOutputParams; } | { pathname: `/hospital/data_up`; params?: Router.UnknownOutputParams; } | { pathname: `/hospital`; params?: Router.UnknownOutputParams; } | { pathname: `/hospital/profile`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/login/signin`; params?: Router.UnknownOutputParams; } | { pathname: `/login/signup`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AddNew${`?${string}` | `#${string}` | ''}` | `/AddNew${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/Profile${`?${string}` | `#${string}` | ''}` | `/Profile${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/doctor${`?${string}` | `#${string}` | ''}` | `/feats/MedicalReport${`?${string}` | `#${string}` | ''}` | `/feats/ResultModal${`?${string}` | `#${string}` | ''}` | `/feats/dhancha${`?${string}` | `#${string}` | ''}` | `/feats/dvit${`?${string}` | `#${string}` | ''}` | `/feats/jagrook${`?${string}` | `#${string}` | ''}` | `/feats/medi-sight${`?${string}` | `#${string}` | ''}` | `/hospital/data_up${`?${string}` | `#${string}` | ''}` | `/hospital${`?${string}` | `#${string}` | ''}` | `/hospital/profile${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/login/signin${`?${string}` | `#${string}` | ''}` | `/login/signup${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AddNew` | `/AddNew`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/Profile` | `/Profile`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `/doctor`; params?: Router.UnknownInputParams; } | { pathname: `/feats/MedicalReport`; params?: Router.UnknownInputParams; } | { pathname: `/feats/ResultModal`; params?: Router.UnknownInputParams; } | { pathname: `/feats/dhancha`; params?: Router.UnknownInputParams; } | { pathname: `/feats/dvit`; params?: Router.UnknownInputParams; } | { pathname: `/feats/jagrook`; params?: Router.UnknownInputParams; } | { pathname: `/feats/medi-sight`; params?: Router.UnknownInputParams; } | { pathname: `/hospital/data_up`; params?: Router.UnknownInputParams; } | { pathname: `/hospital`; params?: Router.UnknownInputParams; } | { pathname: `/hospital/profile`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/login/signin`; params?: Router.UnknownInputParams; } | { pathname: `/login/signup`; params?: Router.UnknownInputParams; };
    }
  }
}
